PdxCodeGuild/class_indri

- anthonyw/README.md
> Added name folder with python nested folder

- .gitignore
> Added name folder with python nested folder & README. 

- mark/python/unit_converter.py
Lab is completed and ready for review.
> Mark python unit converter

- anthonys/python/Notes/python_review.py
- anthonys/python/lab1.py
> Anthonys python unit converter

- noah-initial/python/lab_1.py
Still working on this lab (version 4).
> unit 1 lab submission

- chastity/python/notes/python_review.py
- chastity/python/unit_con.py
Lab for unit converter all four versions complete
> Chastity python unit converter

- noah-initial/python/lab_1.py
Final version of unit converter lab!
> Unit Converter lab Final Version

- anthonys/python/lab2_plus.py
I am going to try and work on type errors now.
> Lab2 complete

- noah-initial/python/blackjack_advice.py
Final submission for blackjack advice lab!
> Submission for blackjack advice Lab

- mark/python/blackjack_advice.py
> Blackjack advice generator lab

- chastity/python/blackjack_advice.py
- chastity/python/blackjack_advices.py
> BlackJack Solutions

- noah-initial/python/blackjack_advice.py
- noah-initial/python/pick6.py
> updated blackjack advice and added the start of pick6 lab

- mark/python/pick_6.py
> Mark pick 6

- mark/python/credit_card_validation.py
> Mark python credit card validation

- anthonys/python/lab4.py
> Anthony credit card validation lab

- chastity/python/credit_val.py
> Credit Card Validation

- noah-initial/python/count_words.py
count words lab completed (version 1)
> Count words lab

- chastity/python/rot_cipher.py
- chastity/python/word_count.py
Incomplete, not ready to merge.
> Word Count incomplete

- anthonys/python/lab6.py
I am not done yet. Are we expected to get the \n out of the string? Been having hard time with it.
> Word Count Lab Finished

- noah-initial/python/automated_readability_index.py
- noah-initial/python/count_words.py
Completed ARI lab (will revisit to clean up but is good to grade!)
> Added completed ARI lab

- anthonys/python/lab7.py
Code doesn't look pretty but it works
> Lab7 Done but might work on making code clearer

- mark/python/atm.py
- mark/python/auto_read_index.py
- mark/python/count_words.py
> Mark python atm

- noah-initial/dad_joke_api.py
> Finished dad joke lab

- anthonys/python/lab9_daddy_jokes.py
Did Part 1 and Part 2. Lab is complete
> Done with daddy jokes lab

- mark/python/auto_read_index.py
- mark/python/dad_jokes.py
> Mark python dad jokes

- noah-initial/quote_api.py
Finished Quote api lab version 2!
> Finished quote api lab

- mark/python/quotes_api.py
> Mark python quotes

- chastity/python/atm.py
- chastity/python/dad_joke.py
The last push erased ATM.py from my VScode, so sending it again to make sure it comes through.
> ATM V1 & V2, Dad Joke

- noah-initial/python/Notes/keys.py
- noah-initial/python/credit_card_validation.py
- noah-initial/python/pick6.py
Grade: pick6 lab
Dont grade: validation lab
> Finished pick6 lab and start of credit card validation lab

- noah-initial/html/html-fundamentals/bio.html
- noah-initial/html/html-fundamentals/styles.css
> Finished Html Bio Lab

- anthonys/python/html/lab1_bio.html
- anthonys/python/lab10_quotes_api.py
> Anthonys bio

- mark/html-css/html-fundamentals/index.html
- mark/html-css/html-fundamentals/styles.css
- mark/html-css/lab1-bio/index.html
- mark/html-css/lab1-bio/style.css
- mark/python/dad_jokes.py
- mark/python/quotes_api.py
> Mark htmlcss lab1 bio

- anthonys/python/html/lab1_bio.html
- anthonys/python/html/lab2_blog.html
I have been figuring out how to make lists into menu options with a side and header nav bars.
> Finished Bio Lab 

- anthonys/python/html/lab1_bio.html
- anthonys/python/html/lab3_framework.html
Making the my HTML like the Army website
> Framework Lab Done

- johnpaul/HTML-CSS/wellsfargo.css
- johnpaul/HTML-CSS/wellsfargo.html
Changed the Davita landing page lab to Wells Fargo Landing page
> chnaged Davita LandPage to wellsfargo LP

- anthonys/python/html/anthonys_burrito.html
Lab is Finished for Form HTML lab
> Anthonys burrito

- anthonys/python/html/anthonys_flask_app.py
- anthonys/python/html/templates/flask.html
- anthonys/python/html/templates/results.html
> Done Flask Lab

- chastity/html_css/order_form/index.html
- chastity/html_css/order_form/style.css
> order form

- mark/html-css/lab2-blog/index.html
- mark/html-css/lab2-blog/styles.css
> Mark htmlcss lab2 blog

- mark/html-css/lab2-blog/index.html
- mark/html-css/lab2-blog/styles.css
- mark/html-css/lab3-company/index.html
- mark/html-css/lab3-company/testing/styles.css
- mark/html-css/lab3-company/testing/test.html
- mark/html-css/lab5-Order-Form/index.html
- mark/html-css/lab5-Order-Form/styles.css
> Mark html lab3 company

- noah-initial/Javascript/Lab 1/index.html
- noah-initial/Javascript/Lab 1/main.js
Completed Javascript Rock paper scissors lab
> Finished rock paper scissors Javascript

- mark/javascript/redo/index.html
- mark/javascript/redo/main.js
- mark/javascript/time_dilation_calculator/Pipfile
- mark/javascript/time_dilation_calculator/index.html
- mark/javascript/time_dilation_calculator/main.js
- mark/javascript/todo_list/index.html
- mark/javascript/todo_list/main.js
- mark/javascript/todo_list/style.css
> Mark js todo list

- mark/javascript/redo/index.html
- mark/javascript/redo/main.js
- mark/javascript/time_dilation_calculator/Pipfile
- mark/javascript/time_dilation_calculator/index.html
- mark/javascript/time_dilation_calculator/main.js
> Mark javascript redo

- mark/javascript/weather_api/.gitignore
- mark/javascript/weather_api/index.html
- mark/javascript/weather_api/main.js
- mark/javascript/weather_api/style.css
> Mark js weather api

- anthonys/javascript/weatherAPI/.gitignore
- anthonys/javascript/weatherAPI/index.js
- anthonys/javascript/weatherAPI/lab07-weather_api.html
> Done with Weather API Lab
